services:
  db:
    image: postgres:15-alpine
    container_name: matheus_ciriaco_db
    environment:
      POSTGRES_USER: fatec_user
      POSTGRES_PASSWORD: fatec_password
      POSTGRES_DB: todolist
    volumes:
      - matheus_ciriaco_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: matheus_ciriaco_api
    restart: always  # <-- Se a API cair, o Docker sobe ela de novo até o banco estar pronto.
    environment:
      DB_HOST: db
    depends_on:
      - db

  healthcheck:
      test: ["CMD", "curl", "-f", "http://136.248.77.234:3027"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Cada arquivo de log terá no máximo 10MB
        max-file: "3"     # O Docker guarda apenas os últimos 3 arquivos (total 30MB) 

  web:
    build: ./frontend
    container_name: matheus_ciriaco_web
    ports:
      - "8027:80"
    depends_on:
      api:
        condition: service_healthy  

volumes:
  matheus_ciriaco_data: